-- Add profile fields for clients and candidates
-- Client fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS company_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS industry VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS company_size VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS contact_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS hire_type VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS engagement_type VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS timeline VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS job_functions JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS specific_needs TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS heard_from VARCHAR(255);

-- Candidate specific fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS country VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS timezone VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS primary_function VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS years_experience VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS "current_role" VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS education VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS english_proficiency VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS availability VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS portfolio_url VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS why_instinctx TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS startup_experience TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS resume_path VARCHAR(500);

